name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install project
      run: make install
    - name: Run application
      run: |
        make run &
        echo "Waiting for 30 seconds to allow the server to start..."
        sleep 30
        echo "Server should now be running. Checking if process is still alive..."
        if pgrep -f "flask run"; then
          echo "Server is running successfully."
          pkill -f "flask run"
        else
          echo "Server failed to start or has stopped."
          exit 1
        fi
